### ISSUE TITLE
Cannot find superadmin.p12 file

### ISSUE THREAD

**Issue by ugochirico** [bitnami/bitnami-docker-ejbca#3]
After setting up the EJCBCA container I was not able to find the file superadmin.p12 that is needed for client authentication to access to the web interface.
The EJBCA documentation says that it is in the folder EJBCA_HOME/p12/superadmin.p12 
But I was not able to find it

Can you help?

**Comment by alemorcuq** [comment]
Hi, @ugochirico.

You can download the certificate from the web application. Just access to `your-installation.tld/ejbca` and go to `Enroll -> Create browser certificate`. You should be able to generate and download the `.p12` file from there.

**Comment by kagstrom2100** [comment]
Hey, so I just set up my first EJBCA server and I'm running into the same problem. I used this guide to do the installation (https://wiki.e-odyssey.net/ejbca/english-tuto)

I tried following the workaround @alemorcuq suggested, but I'm not able to access the web GUI as it says "connection refused" probably cause I'm missing the superadmin certificate.

Any other suggestions?

**Comment by alemorcuq** [comment]
Let's move the conversation to the new ticket instead.

**Comment by padaou** [comment]
Hi. Please how can I download the ejbca virtual machine

**Comment by alemorcuq** [comment]
Unfortunately we don't offer VMs for EJBCA, just containers.

**Comment by padaou** [comment]
OK.  When I tried to install the container on the Ubuntu docker compose, I
could not open the adminweb

Le ven. 16 juil. 2021 14:52, Alejandro Moreno ***@***.***> a
écrit :

**Comment by alemorcuq** [comment]
Please, create a new ticket for the issue you are having, @padaou.
