### ISSUE TITLE
Hey, so I just set up my first EJBCA server and I'm running into the same problem. I used this guide to do the installation (https://wiki.e-odyssey.net/ejbca/english-tuto)

### ISSUE THREAD

**Issue by kagstrom2100** [bitnami/bitnami-docker-ejbca#6]
Hey, so I just set up my first EJBCA server and I'm running into the same problem. I used this guide to do the installation (https://wiki.e-odyssey.net/ejbca/english-tuto)

I tried following the workaround @alemorcuq suggested, but I'm not able to access the web GUI as it says "connection refused" probably cause I'm missing the superadmin certificate.

Any other suggestions?

_Originally posted by @kagstrom2100 in https://github.com/bitnami/bitnami-docker-ejbca/issues/3#issuecomment-822047059_

**Comment by rafariossaa** [comment]
Hi,
  This is what I did:

```console
$ git clone git clone https://github.com/bitnami/bitnami-docker-ejbca
$ cd bitnami-docker-ejbca
$ docker-compose up
``` 
- Wait until images are pulled and containers started
- Browse to: http://localhost:8080/ejbca/
- Click in "Create Browser Certificate", it will request user and password. The default credentials are: `superadmin` / `Bitnami1234`. Then, set the keylength, eg. `RSA 2048 bits`, `ENDUSER` for certificate profile, and click `Enroll`. This will download the superadmin certificate file `superadmin.p12`
- Install the certificate `superadmin.p12` in your browser.
- Once installed, you can access the `Administration` section.

**Comment by kagstrom2100** [comment]
> Hi,
> This is what I did:
> 
> ```
> $ git clone git clone https://github.com/bitnami/bitnami-docker-ejbca
> $ cd bitnami-docker-ejbca
> $ docker-compose up
> ```
> 
> * Wait until images are pulled and containers started
> * Browse to: http://localhost:8080/ejbca/
> * Click in "Create Browser Certificate", it will request user and password. The default credentials are: `superadmin` / `Bitnami1234`. Then, set the keylength, eg. `RSA 2048 bits`, `ENDUSER` for certificate profile, and click `Enroll`. This will download the superadmin certificate file `superadmin.p12`
> * Install the certificate `superadmin.p12` in your browser.
> * Once installed, you can access the `Administration` section.
> 
> Could you give this a try ?

Hey,

Thanks for your reply! I just reinstalled them VM and the cert folder showed up now. Though now I'm stuck at importing the certificate in Windows, I imported it to the computer store and then moved the CA cert to the trusted root certificates. But when I try to access the internal address I assigned it (192.168.1.55) so 192.168.1.55/ejbca I still get the "connection refused error". 
I did try to restart both edge and my computer, but no dice. And suggestions?
Sorry I know the isn't part of the original issue :)

**Comment by rafariossaa** [comment]
Hi,
  Not very sure about this error, maybe a screenshot would help.
  You should check that the url you are using is the correct one, maybe it is not the right IP. In the url you providec, I think you are missing the port.

**Comment by kagstrom2100** [comment]
> Hi,
> Not very sure about this error, maybe a screenshot would help.
> You should check that the url you are using is the correct one, maybe it is not the right IP. In the url you providec, I think you are missing the port.

Hm a screenshot of what? The error message I get when trying to access the site? It's just the standard edge page saying "localhost refused the connection". As for the address I tried it with both "https://192.168.1.55/ejbca" and https://192.168.1.55:"portnumber"/ejbca. But still get the same error, so I'm sure it's the right address. Think it's got something to do with the certificate.

**Comment by kagstrom2100** [comment]
> > Hi,
> > Not very sure about this error, maybe a screenshot would help.
> > You should check that the url you are using is the correct one, maybe it is not the right IP. In the url you providec, I think you are missing the port.
> 
> Hm a screenshot of what? The error message I get when trying to access the site? It's just the standard edge page saying "localhost refused the connection". As for the address I tried it with both "https://192.168.1.55/ejbca" and [https://192.168.1.55:"portnumber"/ejbca](https://192.168.1.55:%22portnumber%22/ejbca). But still get the same error, so I'm sure it's the right address. Think it's got something to do with the certificate.

Actually scratch that, I just got a bit further as when I went to the address using http I got a "cert common name invalid" error. That made me realised that I needed to use the common name for the address instead of the IP. so that'd be "https://ejbcaserver.tpd:portnumber/ejbca" but when I tried that I got "ERR_CONNECTION_CLOSED" instead. Hmm...

**Comment by kagstrom2100** [comment]
So I just fixed it, all I had to do was to enter the domain name instead of the IP (as I mentioned in my last reply). But I you also had to import the superadmin certificate into the edge cert store! Now I'm able to access the site no problem!

**Comment by rafariossaa** [comment]
I am glad you were able to solve the issue.
Thanks for sharing.
