### ISSUE TITLE
Can't override with EJBCA_SERVER_CERT_FILE  

### ISSUE THREAD

**Issue by vchatela** [bitnami/bitnami-docker-ejbca#8]
Hi,

I have initiated EJBCA with initial docker-compose that did not contain EJBCA_SERVER_CERT_FILE and EJBCA_SERVER_CERT_PASSWORD as I wanted to build my own CA. 

I have created a new certificate after this setup, then I tried to replace the keystore.jks to get a new certificate from EJBCA itself.

I have generated the new JKS with new DNS entries etc, then I thought that I could reuse EJBCA_SERVER_CERT_FILE and EJBCA_SERVER_CERT_PASSWORD in order to erase the current keystore.. But no as I could see in the libejbca.sh 

EDIT : following has been fixed by restarting the full stack and not only the ejbca container
> Then I have tried to replace manually the keystore.jks by the new one I had created, but even with same password for keystore and the key, even with same alias etc, can't make it works.

So the question is, how could I replace either the alias used for the certificate, or how to make sure EJBCA_SERVER_CERT_FILE is used whenever there is current certificate in place ?
Thank you
Valentin

**Comment by Mauraza** [comment]
Hi @vchatela,

You can add to your `docker-compose.yaml` the environment variable `EJBCA_SERVER_CERT_FILE` and run again `docker-compose up -d`. 

The environment variables are in https://github.com/bitnami/bitnami-docker-ejbca/blob/master/6/debian-10/rootfs/opt/bitnami/scripts/ejbca-env.sh

**Comment by vchatela** [comment]
> Hi @vchatela,
> 
> You can add to your `docker-compose.yaml` the environment variable `EJBCA_SERVER_CERT_FILE` and run again `docker-compose up -d`.
> 
> The environment variables are in https://github.com/bitnami/bitnami-docker-ejbca/blob/master/6/debian-10/rootfs/opt/bitnami/scripts/ejbca-env.sh

Hi,
I have already added the new environment variable. The issue is that the init script doesn't take it into account!
As I use persistent data then it does not erase old key store.

**Comment by Mauraza** [comment]
Hi @vchatela,

Which init script are you referring to?
Where is your new keystore?

**Comment by vchatela** [comment]
Hi @Mauraza
Referring to https://github.com/bitnami/bitnami-docker-ejbca/blob/master/6/debian-10/rootfs/opt/bitnami/scripts/libejbca.sh
Keystores are local to the docker but when I use the env variable they are not used. Which is conform of how it is implemented within the libejbca.sh but does not seem correct to me

**Comment by juan131** [comment]
Hi @vchatela 

As you can see in the link below, these settings are indeed designed to be overriden:

- https://github.com/bitnami/bitnami-docker-ejbca/blob/master/6/debian-10/rootfs/opt/bitnami/scripts/ejbca-env.sh#L78

The problem is the filesystem is ephemeral. I mean, any change you do in the filesystem will be lost when you recreate the containers and revert back to the original state available in the container image. To avoid this, you can use volumes in as similar way we're mounting a volume to persist the EJBCA data, see:

- https://github.com/bitnami/bitnami-docker-ejbca/blob/master/docker-compose.yml#L18

For instance, you can introduce the changes below in the Docker Compose to mount the keystore from your host:

```diff
version: "2"
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.5
    volumes:
      - "mariadb_data:/bitnami/mariadb"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_ejbca
      - MARIADB_DATABASE=bitnami_ejbca
      - MARIADB_PASSWORD=Bitnami1234
  ejbca:
    image: docker.io/bitnami/ejbca:6
    ports:
      - 8080:8080
      - 8443:8443
    volumes:
      - "ejbca_data:/bitnami/ejbca"
+     - ./certificate.keystore:/certs/certificate.keystore:ro
    environment:
      - EJBCA_DATABASE_HOST=mariadb
      - EJBCA_DATABASE_NAME=bitnami_ejbca
      - EJBCA_DATABASE_USERNAME=bn_ejbca
      - EJBCA_DATABASE_PASSWORD=Bitnami1234
+    - EJBCA_SERVER_CERT_FILE=/certs/certificate.keystore
+    - EJBCA_SERVER_CERT_PASSWORD=FOO

volumes:
  mariadb_data:
    driver: local
  ejbca_data:
    driver: local
```

Does it make sense?

**Comment by vchatela** [comment]
Hello @juan131 
They are "intented" to be overwritten but they are not here : https://github.com/bitnami/bitnami-docker-ejbca/blob/714eb19d7a72af4963f57a0029767d0a5be690a3/6/debian-10/rootfs/opt/bitnami/scripts/libejbca.sh#L574 
The only location where the variable is used is here : 
```
if ! ejbca_is_persisted; then
        info "Deploying EJBCA from scratch"

...
# Check if external keystore
        if [[ -f "$EJBCA_SERVER_CERT_FILE" && -n "$EJBCA_SERVER_CERT_PASSWORD" ]]; then
            info "Using provided server TLS keystore"
            ejbca_keytool_command -importkeystore -noprompt \
                -srckeystore "$EJBCA_SERVER_CERT_FILE" \
                -srcstorepass "$EJBCA_SERVER_CERT_PASSWORD" \
                -destkeystore "$EJBCA_TEMP_KEYSTORE_FILE" \
                -deststorepass "$EJBCA_KEYSTORE_PASSWORD" \
                -deststoretype jks
        fi
```
So because I already have persistant data then it is not taken into account.

I already have my docker compose file with all changes. The problem is not about how I configure it, it is that after initial setup the `EJBCA_SERVER_CERT_FILE` is not taken into account.

**Comment by juan131** [comment]
Hi @vchatela 

> So because I already have persistent data then it is not taken into account.
>
> I already have my docker compose file with all changes. The problem is not about how I configure it, it is that after initial setup the EJBCA_SERVER_CERT_FILE is not taken into account.

That is the expected behavior. Many of the configuration settings that are exposed in this container to be configurable via env. variables (including the keystores) are only taken into account during the 1st run as explained in the link below:

- https://github.com/bitnami/bitnami-docker-ejbca#configuration

> The EJBCA instance can be customized by specifying environment variables on the first run. The following environment variables are available:
>
> ...

If you already have persisted data, you will have to access your container and replace the keystores manually.

**Comment by vchatela** [comment]
Thank you @juan131 for answer.

It seems weird for me to consider an expected behavior to set attributes that are not taken into account.
Basically, I need to setup the PKI server to generate my server certificate, so I can't set this `EJBCA_SERVER_CERT_FILE` at first run. 

So especially for this value and for this container, `EJBCA_SERVER_CERT_FILE` should be used even if I already have initiated the server.

**Comment by juan131** [comment]
Hi @vchatela 

The reason why this setting is only admitted during the 1st boot of the container is avoiding revoking existing certificates. Please note that, by replacing the original certificate, any previously created certificate will be revoked.

**Comment by vchatela** [comment]
Hi @juan131 
I do not agree, I can buy a public certificate and replace the one provided by the PKI itself and it won't revoke it. 
I must go to the interface to revoke it.
So there isn't any reason of restricting to first boot, I can choose whatever certificate to expose on the HTTPS it has nothing to deal with how EJBCA manages certificates.

**Comment by juan131** [comment]
Hi @vchatela 

My colleague @rafariossaa has been taking a look on this. Apparently this is more or less the workflow:

- When EJBCA is started for the 1s time, it generates a CA and a certificate and stores them under `/bitnami/ejbca/tls/keystore.jks` (private keys), and `/bitnami/ejbca/tls/truststore.jks` (public keys).
- Under the keystore a certificate to serve EJBCA via HTTPS is also generated. So there are 2 certs in the keystore: the CA and the certificate for HTTPS.
- When the admin enrolls (Create Browser Certificate option), a new cert is generated for the user (superadmin) and it is signed by the CA in keystore.

So.. That keystore file can not be changed because if you already have certs issued with the CA you are not going to be able to release more certs with that CA. Does it make sense?

Best regards,

Juan Ariza

**Comment by vchatela** [comment]
Hi @juan131 
Thank you for analysis, but in the end there are 2 reasons to use this after initial : 
1. the goal is that if I use EJBCA I want to create a new CA, and so edit the generated End Entity to use my new CA and so generate a new certificate. 
2. One time, the default certificate will expire
In the end I have to replace it either for changes (new DNS, new security requirements like length, use another CA...) or because of expiration.

So it still does not make any sense to limit to initial setup. 

Note : you are wrong in  `/bitnami/ejbca/tls/truststore.jks` there are not the public keys of the `/bitnami/ejbca/tls/keystore.jks`. In fact in `truststore.jks` there are public keys but the one that are used to validate client certificate. In `keystore.jks` there are the private and public keys used for HTTPS but can be from a very different CA than the `truststore.jks`

Example is : 
- `truststore.jks` : create a new CA for client authentication only, and set that admin certificate should come from this CA
- `keystore.jks` : buy an external certificate (like Sectigo) and create a new dedicated JKS

Kind regards

**Comment by juan131** [comment]
Hi @vchatela 

> So it still does not make any sense to limit to initial setup.

Please note that the current logic is not blocking you from editing the CA generated during the 1st boot. It's simply not providing you a way to do so via environment variables.

Both the `keystore.jks` and `truststore.jks` are persisted in a volume mounted in the EJBCA container. Therefore, you can manually modify them at any point. For instance: stopping the EJBCA container and mounting the volume in another container including a text editor OR mounting a volume from the host and edit it from the host (only works locally).

- https://github.com/bitnami/bitnami-docker-ejbca/blob/master/docker-compose.yml#L19

Please note there is also a disadvantage on rewriting the `keystore` based on the `EJBCA_SERVER_CERT_FILE`  every time the container is restarted: whatever changes that are applied to the file while the container is running will be lost forever, and without notifying the user.

> In fact in `truststore.jks` there are public keys but the one that are used to validate client certificate.

You're totally right, thanks for the correction.

**Comment by vchatela** [comment]
Hi @juan131 ,

I understand your vision.

Nevertheless in the end I do see a very few cases where at initial startup we would need to use them, whereas I do see a lot of reasons of using them to replace/select keystore/truststore.jks .

For me it would have been such more easier to simply replace the persistent keystore.jks and truststore.jks by the provide one in the variables and then its all. Like this, user has only to generate the jks he/she wants, put it in a persistent storage on the container then use this variable to use it instead of having to use keytool commands online to update something you do not anymore care because you want to replace it...
So in the end, it would not be at every restart, a basic check of md5sum of both jks would determine if action is required or not.

Kind regards

**Comment by juan131** [comment]
Thanks for sharing your concerns about the UX. @rafariossaa @javsalgar  what do you think? Is it worth to reconsider our current approach?

**Comment by juan131** [comment]
Removing "stale" label. @rafariossaa is on PTO and I want to hear his opinion when he's back.
